version: "3"

services:
    # TM Convention App
    tmconvention:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - /var/www/html/vendor
            - /var/www/html/node_modules
        networks:
            - tmconvention_network
            - mariadb_network

    # Nginx for TM Convention
    tmconvention_nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "86:80"
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - tmconvention
        networks:
            - npm_network
            - tmconvention_network

networks:
    npm_network:
        external: true
    mariadb_network:
        external: true
    tmconvention_network:
        driver: bridge
