version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: tmoneconvention_app
        container_name: tmoneconvention_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - tmoneconvention_network
            - mariadb_network
        environment:
            - "DB_HOST=centralized_mariadb"
            - "DB_PORT=3306"
            - "DB_DATABASE=convention2025_db"
            - "DB_USERNAME=convention2025_user"
            - "DB_PASSWORD=convention2025_password"

    nginx:
        image: nginx:alpine
        container_name: tmoneconvention_nginx
        restart: unless-stopped
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - tmoneconvention_network
            - npm_network

networks:
    tmoneconvention_network:
        driver: bridge
    mariadb_network:
        external: true
    npm_network:
        external: true
