### docker-compose.yml
version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: tmoneconvention_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app_network
            - mariadb_network

    nginx:
        image: nginx:alpine
        container_name: tmoneconvention_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app_network
            - npm_network

networks:
    app_network:
        driver: bridge
    mariadb_network:
        external: true
    npm_network:
        external: true
