# docker-compose.yml
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_vue_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www:delegated
            - .env:/var/www/.env:delegated
            - /var/www/vendor
            - /var/www/node_modules
        networks:
            - npm_network
            - mariadb_network
            - app_network

    php-fpm:
        image: php:8.2-fpm
        container_name: laravel_php_fpm
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www:delegated
            - .env:/var/www/.env:delegated
            - /var/www/vendor
        networks:
            - app_network

networks:
    npm_network:
        external: true
    mariadb_network:
        external: true
    app_network:
        driver: bridge
