<script setup>
const info = (location) => {
    console.log(location);
};
</script>

<template>
    <div class="max-w-screen-xl py-8 mx-auto">
        <div class="px-6 mx-auto max-w-7xl lg:px-8">
            <div class="max-w-2xl mx-auto text-center">
                <h2
                    class="text-3xl font-bold tracking-tight uppercase text-cobalt-blue font-title sm:text-4xl"
                >
                    PWRGAME
                </h2>
                <p class="mt-2 text-lg leading-8 text-gray-500">
                    Products Showcase - M Floor • Physical Challenges - G Floor
                </p>
            </div>
            <div
                class="grid max-w-2xl grid-cols-1 gap-8 mx-auto mt-8 auto-rows-fr lg:mx-0 lg:max-w-none lg:grid-cols-2"
            >
                <div>
                    <!-- Image Map Generated by http://www.image-map.net/ -->
                    <img
                        src="/images/PWRGame-Map-02.png"
                        usemap="#image-map-2"
                    />

                    <map name="image-map-2">
                        <area
                            @click.prevent="info('1')"
                            target=""
                            alt="Station 1"
                            title="Station 1"
                            href="#"
                            coords="86,240,39"
                            shape="circle"
                        />
                        <area
                            @click.prevent="info('2')"
                            target=""
                            alt="Station 2"
                            title="Station 2"
                            href="#"
                            coords="77,161,37"
                            shape="circle"
                        />
                        <area
                            @click.prevent="info('3')"
                            target=""
                            alt="Station 3"
                            title="Station 3"
                            href="#"
                            coords="85,79,37"
                            shape="circle"
                        />
                        <area
                            @click.prevent="info('4')"
                            target=""
                            alt="Station 4"
                            title="Station 4"
                            href="#"
                            coords="351,163,39"
                            shape="circle"
                        />
                        <area
                            @click.prevent="info('5')"
                            target=""
                            alt="Station 5"
                            title="Station 5"
                            href="#"
                            coords="434,159,38"
                            shape="circle"
                        />
                        <area
                            @click.prevent="info('6')"
                            target=""
                            alt="Station 6"
                            title="Station 6"
                            href="#"
                            coords="410,353,36"
                            shape="circle"
                        />
                        <area
                            @click.prevent="info('7')"
                            target=""
                            alt="Station 7"
                            title="Station 7"
                            href="#"
                            coords="411,425,36"
                            shape="circle"
                        />
                        <area
                            @click.prevent="info('8')"
                            target=""
                            alt="Station 8"
                            title="Station 8"
                            href="#"
                            coords="412,500,34"
                            shape="circle"
                        />
                    </map>
                </div>
                <div>
                    <!-- Image Map Generated by http://www.image-map.net/ -->
                    <img
                        src="/images/PWRGame-Map-01.png"
                        usemap="#image-map-1"
                    />

                    <map name="image-map-1">
                        <area
                            @click.prevent="info('9')"
                            target=""
                            alt="Station 9"
                            title="Station 9"
                            href="#"
                            coords="51,366,36"
                            shape="circle"
                        />
                        <area
                            @click.prevent="info('10')"
                            target=""
                            alt="Station 10"
                            title="Station 10"
                            href="#"
                            coords="375,474,36"
                            shape="circle"
                        />
                        <area
                            @click.prevent="info('11A')"
                            target=""
                            alt="Station 11A"
                            title="Station 11A"
                            href="#"
                            coords="478,369,37"
                            shape="circle"
                        />
                        <area
                            @click.prevent="info('11B')"
                            target=""
                            alt="Station 11B"
                            title="Station 11B"
                            href="#"
                            coords="57,536,33"
                            shape="circle"
                        />
                        <area
                            @click.prevent="info('12A')"
                            target=""
                            alt="Station 12A"
                            title="Station 12A"
                            href="#"
                            coords="550,185,37"
                            shape="circle"
                        />
                        <area
                            @click.prevent="info('12B')"
                            target=""
                            alt="Station 12B"
                            title="Station 12B"
                            href="#"
                            coords="545,418,36"
                            shape="circle"
                        />
                        <area
                            @click.prevent="info('13A')"
                            target=""
                            alt="Station 13A"
                            title="Station 13A"
                            href="#"
                            coords="470,60,35"
                            shape="circle"
                        />
                        <area
                            @click.prevent="info('13B')"
                            target=""
                            alt="Station 13B"
                            title="Station 13B"
                            href="#"
                            coords="300,46,35"
                            shape="circle"
                        />
                    </map>
                </div>
            </div>
        </div>
    </div>
</template>
