<script setup>
import SecondaryButton from "@/Components/SecondaryButton.vue";
import Modal from "@/Components/Modal.vue";
import Station01 from "./Modals/Station01.vue";
import Station02 from "./Modals/Station02.vue";
import Station03 from "./Modals/Station03.vue";
import Station04 from "./Modals/Station04.vue";
import Station05 from "./Modals/Station05.vue";
import Station06 from "./Modals/Station06.vue";
import Station07 from "./Modals/Station07.vue";
import Station08 from "./Modals/Station08.vue";
import { ref } from "vue";

const showingModal = ref(false);
const selectedStation = ref(null);

const openModal = (location) => {
    selectedStation.value = location;
    showingModal.value = true;
};

const closeModal = () => {
    showingModal.value = false;
};
</script>

<template>
    <div class="max-w-screen-xl py-8 mx-auto">
        <div class="px-6 mx-auto max-w-7xl lg:px-8">
            <div class="max-w-2xl mx-auto text-center">
                <h2
                    class="text-3xl font-bold tracking-tight uppercase text-cobalt-blue font-title sm:text-4xl"
                >
                    PWRGAME
                </h2>
                <p class="mt-2 text-lg leading-8 text-gray-500">
                    Products Showcase - M Floor • Physical Challenges - G Floor
                </p>
            </div>
            <div
                class="grid max-w-2xl grid-cols-1 gap-8 mx-auto mt-8 auto-rows-fr lg:mx-0 lg:max-w-none lg:grid-cols-2"
            >
                <div>
                    <!-- Image Map Generated by http://www.image-map.net/ -->
                    <img
                        src="/images/PWRGame-Map-02.png"
                        usemap="#image-map-2"
                    />

                    <map name="image-map-2">
                        <area
                            @click.prevent="openModal('01')"
                            target=""
                            alt="Station 1"
                            title="Station 1"
                            href="#"
                            coords="86,240,39"
                            shape="circle"
                        />
                        <area
                            @click.prevent="openModal('02')"
                            target=""
                            alt="Station 2"
                            title="Station 2"
                            href="#"
                            coords="77,161,37"
                            shape="circle"
                        />
                        <area
                            @click.prevent="openModal('03')"
                            target=""
                            alt="Station 3"
                            title="Station 3"
                            href="#"
                            coords="85,79,37"
                            shape="circle"
                        />
                        <area
                            @click.prevent="openModal('04')"
                            target=""
                            alt="Station 4"
                            title="Station 4"
                            href="#"
                            coords="351,163,39"
                            shape="circle"
                        />
                        <area
                            @click.prevent="openModal('05')"
                            target=""
                            alt="Station 5"
                            title="Station 5"
                            href="#"
                            coords="434,159,38"
                            shape="circle"
                        />
                        <area
                            @click.prevent="openModal('06')"
                            target=""
                            alt="Station 6"
                            title="Station 6"
                            href="#"
                            coords="410,353,36"
                            shape="circle"
                        />
                        <area
                            @click.prevent="openModal('07')"
                            target=""
                            alt="Station 7"
                            title="Station 7"
                            href="#"
                            coords="411,425,36"
                            shape="circle"
                        />
                        <area
                            @click.prevent="openModal('08')"
                            target=""
                            alt="Station 8"
                            title="Station 8"
                            href="#"
                            coords="412,500,34"
                            shape="circle"
                        />
                    </map>
                </div>
                <div>
                    <!-- Image Map Generated by http://www.image-map.net/ -->
                    <img
                        src="/images/PWRGame-Map-01.png"
                        usemap="#image-map-1"
                    />

                    <map name="image-map-1">
                        <area
                            @click.prevent=""
                            target=""
                            alt="Station 9"
                            title="Station 9"
                            href="#"
                            coords="51,366,36"
                            shape="circle"
                        />
                        <area
                            @click.prevent=""
                            target=""
                            alt="Station 10"
                            title="Station 10"
                            href="#"
                            coords="375,474,36"
                            shape="circle"
                        />
                        <area
                            @click.prevent=""
                            target=""
                            alt="Station 11A"
                            title="Station 11A"
                            href="#"
                            coords="478,369,37"
                            shape="circle"
                        />
                        <area
                            @click.prevent=""
                            target=""
                            alt="Station 11B"
                            title="Station 11B"
                            href="#"
                            coords="57,536,33"
                            shape="circle"
                        />
                        <area
                            @click.prevent=""
                            target=""
                            alt="Station 12A"
                            title="Station 12A"
                            href="#"
                            coords="550,185,37"
                            shape="circle"
                        />
                        <area
                            @click.prevent=""
                            target=""
                            alt="Station 12B"
                            title="Station 12B"
                            href="#"
                            coords="545,418,36"
                            shape="circle"
                        />
                        <area
                            @click.prevent=""
                            target=""
                            alt="Station 13A"
                            title="Station 13A"
                            href="#"
                            coords="470,60,35"
                            shape="circle"
                        />
                        <area
                            @click.prevent=""
                            target=""
                            alt="Station 13B"
                            title="Station 13B"
                            href="#"
                            coords="300,46,35"
                            shape="circle"
                        />
                    </map>
                </div>
            </div>
        </div>
    </div>

    <Modal :show="showingModal" @close="closeModal">
        <div class="p-6">
            <Station01 v-if="selectedStation == '01'" />
            <Station02 v-if="selectedStation == '02'" />
            <Station03 v-if="selectedStation == '03'" />
            <Station04 v-if="selectedStation == '04'" />
            <Station05 v-if="selectedStation == '05'" />
            <Station06 v-if="selectedStation == '06'" />
            <Station07 v-if="selectedStation == '07'" />
            <Station08 v-if="selectedStation == '08'" />

            <div class="flex justify-end mt-6">
                <SecondaryButton @click="closeModal"> Close </SecondaryButton>
            </div>
        </div>
    </Modal>
</template>
